{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd21f949-6bf9-44f6-a8e0-747546b6dd5c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import random\n",
    "\n",
    "# =========================\n",
    "# DATA STRUCTURES\n",
    "# =========================\n",
    "\n",
    "class Star:\n",
    "    def __init__(self, star_type, radiation):\n",
    "        self.star_type = star_type  # \"M\" or \"G\"\n",
    "        self.radiation = radiation  # 0–10\n",
    "\n",
    "\n",
    "class Planet:\n",
    "    def __init__(self, geothermal, ocean, atmosphere, silica, tectonics, age, star):\n",
    "        self.geothermal = geothermal      # 0–10\n",
    "        self.ocean = ocean                # True/False\n",
    "        self.atmosphere = atmosphere      # \"reducing\", \"neutral\", \"oxidizing\"\n",
    "        self.silica = silica              # 0–10\n",
    "        self.tectonics = tectonics        # 0–10\n",
    "        self.age = age                    # Ga\n",
    "        self.star = star\n",
    "\n",
    "\n",
    "# =========================\n",
    "# ATMOSPHERE EVOLUTION\n",
    "# =========================\n",
    "\n",
    "def evolve_atmosphere(p):\n",
    "    if p.age < 2.5:\n",
    "        p.atmosphere = \"reducing\"\n",
    "    elif p.age < 3.0:\n",
    "        p.atmosphere = \"neutral\"\n",
    "    else:\n",
    "        p.atmosphere = \"oxidizing\"\n",
    "    return p\n",
    "\n",
    "\n",
    "# =========================\n",
    "# PLANET EVOLUTION\n",
    "# =========================\n",
    "\n",
    "def evolve_planet(p, steps=20):\n",
    "    for _ in range(steps):\n",
    "        p.age += 0.1\n",
    "\n",
    "        p.geothermal = max(0, p.geothermal - 0.05)\n",
    "        p.tectonics = max(0, p.tectonics - 0.02)\n",
    "\n",
    "        p = evolve_atmosphere(p)\n",
    "\n",
    "        # ocean loss risk\n",
    "        if random.random() < (p.star.radiation / 100):\n",
    "            p.ocean = False\n",
    "\n",
    "    return p\n",
    "\n",
    "\n",
    "# =========================\n",
    "# EMERGENCE SCORE\n",
    "# =========================\n",
    "\n",
    "def emergence_score(p):\n",
    "    score = 0\n",
    "\n",
    "    if p.ocean:\n",
    "        score += 3\n",
    "\n",
    "    score += 0.6 * p.geothermal\n",
    "    score += 0.5 * p.silica\n",
    "\n",
    "    # tectonics: optimal mid-range (not linear)\n",
    "    score += 1 - abs(p.tectonics - 5) / 5\n",
    "\n",
    "    return max(score, 0)\n",
    "\n",
    "\n",
    "# =========================\n",
    "# PHASE CLASSIFICATION\n",
    "# =========================\n",
    "\n",
    "def classify_phase(p, emergence):\n",
    "\n",
    "    if emergence < 3:\n",
    "        return 0  # prebiotic\n",
    "\n",
    "    elif emergence < 6:\n",
    "        return 1  # hydrothermal biosphere\n",
    "\n",
    "    elif emergence < 9:\n",
    "        return 2  # marine biosphere\n",
    "\n",
    "    else:\n",
    "        return 3  # advanced / oxygen-influenced biosphere\n",
    "\n",
    "\n",
    "# =========================\n",
    "# PRESERVATION MODEL\n",
    "# =========================\n",
    "\n",
    "def preservation_probability(p):\n",
    "\n",
    "    silica = p.silica / 10\n",
    "    stability = 1 - abs(p.tectonics - 5) / 5\n",
    "    thermal_stress = 1 - (p.geothermal / 10)\n",
    "\n",
    "    return max(0, min(1,\n",
    "        0.5 * silica +\n",
    "        0.3 * stability +\n",
    "        0.2 * thermal_stress\n",
    "    ))\n",
    "\n",
    "\n",
    "# =========================\n",
    "# DETECTABILITY MODEL\n",
    "# =========================\n",
    "\n",
    "def detectability_score(p, phase):\n",
    "\n",
    "    signal = phase * 2.5  # smooth scaling\n",
    "\n",
    "    if p.ocean:\n",
    "        signal += 2\n",
    "\n",
    "    if p.atmosphere == \"oxidizing\":\n",
    "        signal += 2\n",
    "\n",
    "    noise = p.star.radiation * 0.3\n",
    "\n",
    "    return max(signal - noise, 0)\n",
    "\n",
    "\n",
    "# =========================\n",
    "# BIOSEARCH CORE SCORE\n",
    "# =========================\n",
    "\n",
    "def biosearch_score(p):\n",
    "\n",
    "    emergence = emergence_score(p)\n",
    "    phase = classify_phase(p, emergence)\n",
    "    preservation = preservation_probability(p)\n",
    "    detectability = detectability_score(p, phase)\n",
    "\n",
    "    # normalize emergence to 0–1 range\n",
    "    emergence_n = min(emergence / 10, 1)\n",
    "\n",
    "    total = (\n",
    "        0.4 * emergence_n +\n",
    "        0.3 * preservation +\n",
    "        0.3 * (detectability / 10)\n",
    "    )\n",
    "\n",
    "    return total, phase"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "20d08c38-33c3-4acb-b722-bae9a78ec998",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Mars analog\n",
    "mars_star = Star(\"G\", radiation=4)\n",
    "\n",
    "mars = Planet(\n",
    "    geothermal=2,\n",
    "    ocean=False,\n",
    "    atmosphere=\"neutral\",\n",
    "    silica=6,\n",
    "    tectonics=2,\n",
    "    age=4.5,\n",
    "    star=mars_star\n",
    ")\n",
    "\n",
    "# run model\n",
    "mars = evolve_planet(mars, steps=5)\n",
    "\n",
    "score, phase = biosearch_score(mars)\n",
    "\n",
    "print(\"=== BIOSEARCH TEST: MARS ===\")\n",
    "print(\"Score:\", round(score, 2))\n",
    "print(\"Phase:\", phase)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
